/** @format */

export let data = [
	{
		id: 0,
		title: "Slide 1",
		description: "This is the first slide",
		image: "images/woman/w1.2.jpg",
		price: 10,
		discount: 5,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 1,
		title: "T-Shirt",
		description: "This is the second slide",
		image: "images/woman/w2.3.jpg",
		price: 20,
		discount: 10,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green"],
		size: ["s", "m", "L", "XL"],
	},

	{
		id: 2,
		title: "Pent",
		description: "This is the third slide",
		image: "images/woman/w2.4.jpg",
		price: 30,
		discount: 7,
		for: ["Men", "Boys"],
		catagary: ["Shirts", "Sweatshirts"],
		brand: ["nike", "puma", "addidas"],
		color: ["blue"],
		size: ["s", "m", "L", "XL"],
	},

	{
		id: 3,
		title: "Slide 4",
		description: "This is the third slide",
		image: "images/woman/w3.2.jpg",
		price: 40,
		discount: 12,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 4,
		title: "Slide 5",
		description: "This is the third slide",
		image: "images/woman/w4.2.jpg",
		price: 50,
		discount: 8,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 5,
		title: "Slide 6",
		description: "This is the third slide",
		image: "images/woman/w4.1.jpg",
		price: 60,
		discount: 15,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 6,
		title: "Slide 7",
		description: "This is the third slide",
		image: "images/woman/w6.2.jpg",
		price: 70,
		discount: 10,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 7,
		title: "Slide 8",
		description: "This is the third slide",
		image: "images/woman/w7.2.jpg",
		price: 80,
		discount: 20,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 8,
		title: "Slide 9",
		description: "This is the third slide",
		image: "images/woman/w7.jpg",
		price: 90,
		discount: 18,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 9,
		title: "Slide 10",
		description: "This is the third slide",
		image: "images/woman/w5.1.jpg",
		price: 100,
		discount: 25,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},
];

export const catagary = [
	{
		title: "Men's Clothing",
		image: "images/woman/w5.1.jpg",
		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Jackets",
		li5: "Sweaters",
	},
	{
		title: "Women's Clothing",
		image: "images/woman/w5.1.jpg",
		li1: "Dresses",
		li2: "Skirts",
		li3: "Pants",
		li4: "Jackets",
		li5: "Shoes",
	},
	{
		title: "Boys' Clothing",
		image: "images/woman/w5.1.jpg",
		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Sweaters",
		li5: "Jackets",
	},
	{
		title: "Girlss' Clothing",
		image: "images/woman/w5.1.jpg",
		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Sweaters",
		li5: "Jackets",
	},
];
