/** @format */

export let data = [
	{
		id: 0,
		title: "Slide 1",
		description: "This is the first slide",
		image: "images/woman/beautiful-young-woman-with-curly-hair-fashionable-hat-with-classic-gray-coat-walks-city-autumn-day_338491-12021-small.png",
		price: 10,
		discount: 5,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green"],
		size: ["m", "L"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 1,
		title: "T-Shirt",
		description: "This is the second slide",
		image: "images/woman/blonde-girl-model-grey-oversize-jacket-hat-posing-with-package-with-fishes-studio_165383-183-small.png",
		price: 20,
		discount: 10,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
	},

	{
		id: 2,
		title: "Pent",
		description: "This is the third slide",
		image: "images/woman/longlegged-young-woman-yellow-jacket-sexy-outfit-posing-with-cute-dog-chihuahua_179135-243-small.png",
		price: 30,
		discount: 7,
		for: ["Women"],
		catagary: ["Shirts", "Sweatshirts"],
		brand: ["nike", "puma", "addidas"],
		color: ["blue"],
		size: ["m", "L"],
	},

	{
		id: 3,
		title: "Slide 4",
		description: "This is the third slide",
		image: "images/woman/portrait-astonished-woman-wearing-straw-hat-fluffy-skirt-smiling-holding-smartphone_171337-29582-small.png",
		price: 40,
		discount: 12,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 4,
		title: "Slide 5",
		description: "This is the third slide",
		image: "images/woman/portrait-smiling-young-woman-against-white-background_1048944-30767808-small.png",
		price: 50,
		discount: 8,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green"],
		size: ["s", "m"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 5,
		title: "Slide 6",
		description: "This is the third slide",
		image: "images/woman/pretty-blonde-girl-with-freckles-yellow-outfit-straw-hat-yellow_165383-71-small.png",
		price: 60,
		discount: 15,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 6,
		title: "Slide 7",
		description: "This is the third slide",
		image: "images/woman/sexy-girl-with-purple-hair-tattoo-body-posing-grey-background-perfect-woman-gray-jeans-t-shirt-bright-beautiful-makeup_91497-7151-small.png",
		price: 70,
		discount: 10,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["green", "blue"],
		size: ["m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 7,
		title: "Slide 8",
		description: "This is the third slide",
		image: "images/woman/urban-street-style-girl-details-everyday-look-casual-beige-outfit-accessories-bucket-hat-trendy-minimalist-monochrome-fashion_161568-12246-small.png",
		price: 80,
		discount: 20,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 8,
		title: "Slide 9",
		description: "This is the third slide",
		image: "images/woman/young-woman-black-hat-walking-outside-street_1303-28804-small.png",
		price: 90,
		discount: 18,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["green"],
		size: ["s", "m"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 9,
		title: "Slide 10",
		description: "This is the third slide",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",
		price: 100,
		discount: 25,
		for: ["Women", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "blue"],
		size: ["s", "m", "L"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 10,
		title: "Men's Casual Shirt",
		description: "A comfortable casual shirt for men.",
		image: "images/men/beautiful-brutal-tanned-hipster-man-black-shirt-hat-glasses_149155-1787-small.png",
		price: 35,
		discount: 5,
		for: ["Men"],
		catagary: ["Shirts", "Sweatshirts"],
		brand: ["nike", "puma"],
		color: ["blue", "white"],
		size: ["m", "L", "XL"],
	},

	{
		id: 11,
		title: "Men's Sports T-shirt",
		description: "Perfect for workouts or casual wear.",
		image: "images/men/business-man-sunglasses-fashion-studio-with-pride-gray-background-as-lawyer-male-person-serious-confidence-career-growth-opportunity-with-style-classy-elegant_590464-470932-small.png",
		price: 25,
		discount: 3,
		for: ["Men"],
		catagary: ["Tshirts", "Sweatshirts"],
		brand: ["nike", "addidas"],
		color: ["black", "green"],
		size: ["s", "m", "L"],
	},

	{
		id: 12,
		title: "Men's Jacket",
		description: "Stylish winter jacket for men.",
		image: "images/men/full-length-fashionable-young-man-casual-wear-adjusting-hat-while-standing-against-brown-wall_425904-3348-small.png",
		price: 60,
		discount: 10,
		for: ["Men"],
		catagary: ["Jackets"],
		brand: ["puma", "addidas"],
		color: ["black", "grey", "navy"],
		size: ["m", "L", "XL"],
	},

	{
		id: 13,
		title: "Men's Hoodie",
		description: "Casual hoodie for men, ideal for layering.",
		image: "images/men/full-length-handsome-young-man-looking-camera-while-walking-against-blue-wall_425904-2957-small.png",
		price: 40,
		discount: 7,
		for: ["Men"],
		catagary: ["Sweatshirts"],
		brand: ["nike", "puma"],
		color: ["red", "blue"],
		size: ["L", "XL"],
	},

	{
		id: 14,
		title: "Boys' T-shirt",
		description: "A fun graphic T-shirt for boys.",
		image: "images/men/onfident-young-man-stylish-darkhaired-man-standing-holding-one-hand-trousers-pocket-looking_386167-2361-small.png",
		price: 15,
		discount: 2,
		for: ["Boys"],
		catagary: ["Tshirts"],
		brand: ["puma", "addidas"],
		color: ["blue", "yellow"],
		size: ["s", "m"],
	},

	{
		id: 15,
		title: "Boys' Jeans",
		description: "Comfortable jeans for boys.",
		image: "images/men/stylish-handsome-fashionable-young-man-smart-casual-wear-posing-against-white-background_425904-25931-small.png",
		price: 25,
		discount: 3,
		for: ["Boys"],
		catagary: ["Pants"],
		brand: ["nike", "puma"],
		color: ["blue", "black"],
		size: ["s", "m"],
	},

	{
		id: 16,
		title: "Men's Formal Shirt",
		description: "Elegant formal shirt for men.",
		image: "images/men/thinking-businessman-fashion-studio-clothes-trendy-smart-casual-work-male-model-jacket-idea-outfit-elegance-confidence-luxury-apparel-by-gray-background_590464-413823-small.png",
		price: 50,
		discount: 12,
		for: ["Men"],
		catagary: ["Shirts"],
		brand: ["addidas", "puma"],
		color: ["white", "blue"],
		size: ["m", "L", "XL"],
	},

	{
		id: 17,
		title: "Boys' Winter Jacket",
		description: "Warm jacket for boys during winter.",
		image: "images/men/trendy-male-outfit-young-handsome-man-stylish-jacket-sunglasses-posing-purple-background-neon-light-concept-emotions-fashion-lifestyle_489646-23852-small.png",
		price: 45,
		discount: 6,
		for: ["Boys"],
		catagary: ["Jackets"],
		brand: ["puma", "nike"],
		color: ["green", "black"],
		size: ["m", "L"],
	},

	{
		id: 18,
		title: "Men's  Shorts",
		description: "Lightweight shorts for running.",
		image: "images/men/full-length-portrait-casual-man-standing-with-legs-crossed-gray-wall_171337-83289-small.png",
		price: 20,
		discount: 2,
		for: ["Men"],
		catagary: ["Shorts"],
		brand: ["nike", "addidas"],
		color: ["black", "grey"],
		size: ["s", "m", "L", "XL"],
	},

	{
		id: 19,
		title: "Boys' Sweatshirt",
		description: "Cozy sweatshirt for boys.",
		image: "images/men/young-handsome-man-wearing-jeans-jaket-studio_149155-3521-small.png",
		price: 30,
		discount: 5,
		for: ["Boys"],
		catagary: ["Sweatshirts"],
		brand: ["nike", "addidas"],
		color: ["red", "blue"],
		size: ["s", "m", "L"],
	},
];

export const catagary = [
	{
		title: "Men's Clothing",
		image: "images/men/full-length-fashionable-young-man-casual-clothing-adjusting-eyewear-with-smile-while-standing-against-red-wall_425904-4134-small.png",
		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Jackets",
		li5: "Sweaters",
	},
	{
		title: "Women's Clothing",
		image: "images/woman/portrait-woman-suit-blazer-fashion-glamor-isolated-background-high-quality-photo_163305-249375-small.png",
		li1: "Dresses",
		li2: "Skirts",
		li3: "Pants",
		li4: "Jackets",
		li5: "Shoes",
	},
	{
		title: "Boys' Clothing",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",

		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Sweaters",
		li5: "Jackets",
	},
	{
		title: "Girlss' Clothing",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",

		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Sweaters",
		li5: "Jackets",
	},
];
