/** @format */

export let data = [
	{
		id: 0,
		title: "Slide 1",
		description: "This is the first slide",
		image: "images/woman/beautiful-young-woman-with-curly-hair-fashionable-hat-with-classic-gray-coat-walks-city-autumn-day_338491-12021-small.png",
		price: 10,
		discount: 5,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 1,
		title: "T-Shirt",
		description: "This is the second slide",
		image: "images/woman/blonde-girl-model-grey-oversize-jacket-hat-posing-with-package-with-fishes-studio_165383-183-small.png",

		price: 20,
		discount: 10,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green"],
		size: ["s", "m", "L", "XL"],
	},

	{
		id: 2,
		title: "Pent",
		description: "This is the third slide",
		image: "images/woman/longlegged-young-woman-yellow-jacket-sexy-outfit-posing-with-cute-dog-chihuahua_179135-243-small.png",
		price: 30,
		discount: 7,
		for: ["Men", "Boys"],
		catagary: ["Shirts", "Sweatshirts"],
		brand: ["nike", "puma", "addidas"],
		color: ["blue"],
		size: ["s", "m", "L", "XL"],
	},

	{
		id: 3,
		title: "Slide 4",
		description: "This is the third slide",
		image: "images/woman/portrait-astonished-woman-wearing-straw-hat-fluffy-skirt-smiling-holding-smartphone_171337-29582-small.png",
		price: 40,
		discount: 12,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 4,
		title: "Slide 5",
		description: "This is the third slide",
		image: "images/woman/portrait-smiling-young-woman-against-white-background_1048944-30767808-small.png",
		price: 50,
		discount: 8,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 5,
		title: "Slide 6",
		description: "This is the third slide",
		image: "images/woman/pretty-blonde-girl-with-freckles-yellow-outfit-straw-hat-yellow_165383-71-small.png",
		price: 60,
		discount: 15,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 6,
		title: "Slide 7",
		description: "This is the third slide",
		image: "images/woman/sexy-girl-with-purple-hair-tattoo-body-posing-grey-background-perfect-woman-gray-jeans-t-shirt-bright-beautiful-makeup_91497-7151-small.png",
		price: 70,
		discount: 10,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 7,
		title: "Slide 8",
		description: "This is the third slide",
		image: "images/woman/urban-street-style-girl-details-everyday-look-casual-beige-outfit-accessories-bucket-hat-trendy-minimalist-monochrome-fashion_161568-12246-small.png",
		price: 80,
		discount: 20,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 8,
		title: "Slide 9",
		description: "This is the third slide",
		image: "images/woman/young-woman-black-hat-walking-outside-street_1303-28804-small.png",
		price: 90,
		discount: 18,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},

	{
		id: 9,
		title: "Slide 10",
		description: "This is the third slide",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",
		price: 100,
		discount: 25,
		for: ["Men", "Women", "Boys", "Girls"],
		catagary: ["Tshirts", "Shirts", "Dresses", "Sweatshirts", "Jackets"],
		brand: ["nike", "puma", "addidas"],
		color: ["red", "green", "blue"],
		size: ["s", "m", "L", "XL"],
		comments: [{ name: "bharat ladva", comment: "sdfgh" }],
	},
];

export const catagary = [
	{
		title: "Men's Clothing",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",
		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Jackets",
		li5: "Sweaters",
	},
	{
		title: "Women's Clothing",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",
		li1: "Dresses",
		li2: "Skirts",
		li3: "Pants",
		li4: "Jackets",
		li5: "Shoes",
	},
	{
		title: "Boys' Clothing",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",

		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Sweaters",
		li5: "Jackets",
	},
	{
		title: "Girlss' Clothing",
		image: "images/woman/young-woman-elegant-black-dress-summer-hat_178605-146-small.png",

		li1: "T-Shirts",
		li2: "Shirts",
		li3: "Pants",
		li4: "Sweaters",
		li5: "Jackets",
	},
];
